server:
 ssl:
    key-store: classpath:lekachcerts.jks
    key-store-type: pkcs12
    key-store-password: lekachibm
    key-password: lekachibm 
    key-alias: lekachTSL
    port: 8080
spring: 
  banner: 
    location: classpath:src/main/resources/banner.txt

api: 
  version: 1 